<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修3、pytest -- 编写断言' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>3、pytest -- 编写断言</center></div><div class='banquan'>原文出处:本文由博客园博主luizyao提供。<br/>
原文连接:https://www.cnblogs.com/luizyao/p/11506664.html</div><br>
    <div class="toc">
    <p class="toc-title">目录</p>
    <div class="toc-list">
        <ul>
        <li><a href="#使用assert编写断言">1. 使用<code>assert</code>编写断言</a></li>
        <li><a href="#编写触发期望异常的断言">2. 编写触发期望异常的断言</a></li>
        <li><a href="#特殊数据结构比较时的优化">3. 特殊数据结构比较时的优化</a></li>
        <li><a href="#为失败断言添加自定义的说明">4. 为失败断言添加自定义的说明</a></li>
        <li><a href="#关于断言自省的细节">5. 关于断言自省的细节</a><ul>
        <li><a href="#复写缓存文件">5.1. 复写缓存文件</a></li>
        <li><a href="#去使能断言自省">5.2. 去使能断言自省</a></li>
        </ul></li>
        </ul>
    </div>
</div>
<h2 id="使用assert编写断言">1. 使用<code>assert</code>编写断言</h2>
<p><code>pytest</code>允许你使用<code>python</code>标准的<code>assert</code>表达式写断言；</p>
<p>例如，你可以这样做：</p>
<pre><code><code># src/chapter-3/test_sample.py

def func(x):
    return x + 1


def test_sample():
    assert func(3) == 5</code></pre>
<p>如果这个断言失败，你会看到<code>func(3)</code>实际的返回值<code>+  where 4 = func(3)</code>：</p>
<pre class="bash"><code>$ pipenv run pytest -q src/chapter-3/test_sample.py 
F                                                                 [100%]
=============================== FAILURES ================================
______________________________ test_sample ______________________________

    def test_sample():
&gt;       assert func(3) == 5
E       assert 4 == 5
E        +  where 4 = func(3)

src/chapter-3/test_sample.py:28: AssertionError
1 failed in 0.05s</code></pre>
<p><code>pytest</code>支持显示常见的<code>python</code>子表达式的值，包括：调用、属性、比较、二进制和一元运算符等（可以参考<a href="https://docs.pytest.org/en/latest/example/reportingdemo.html#tbreportdemo">这个例子</a> ）;</p>
<p>这允许你在没有模版代码参考的情况下，可以使用的<code>python</code>的数据结构，而无须担心自省丢失的问题；</p>
<p>同时，你也可以为断言指定了一条说明信息，用于失败时的情况说明：</p>
<pre><code><code>assert a % 2 == 0, &quot;value was odd, should be even&quot;</code></pre>
<h2 id="编写触发期望异常的断言">2. 编写触发期望异常的断言</h2>
<p>你可以使用<code>pytest.raises()</code>作为上下文管理器，来编写一个触发期望异常的断言：</p>
<pre><code><code>import pytest


def myfunc():
    raise ValueError(&quot;Exception 123 raised&quot;)


def test_match():
    with pytest.raises(ValueError):
        myfunc()</code></pre>
<p>当用例没有返回<code>ValueError</code>或者没有异常返回时，断言判断失败；</p>
<p>如果你希望同时访问异常的属性，可以这样：</p>
<pre><code><code>import pytest


def myfunc():
    raise ValueError(&quot;Exception 123 raised&quot;)


def test_match():
    with pytest.raises(ValueError) as excinfo:
        myfunc()
    assert &#39;123&#39; in str(excinfo.value)</code></pre>
<p>其中，<code>excinfo</code>是<code>ExceptionInfo</code>的一个实例，它封装了异常的信息；常用的属性包括：<code>.type</code>、<code>.value</code>和<code>.traceback</code>；</p>
<blockquote>
<p>注意：</p>
<p>在上下文管理器的作用域中，<code>raises</code>代码必须是最后一行，否则，其后面的代码将不会执行；所以，如果上述例子改成：</p>
<pre><code><code>def test_match():
  with pytest.raises(ValueError) as excinfo:
      myfunc()
      assert &#39;456&#39; in str(excinfo.value)</code></pre>
<p>则测试将永远成功，因为<code>assert '456' in str(excinfo.value)</code>并不会执行；</p>
</blockquote>
<p>你也可以给<code>pytest.raises()</code>传递一个关键字参数<code>match</code>，来测试异常的字符串表示<code>str(excinfo.value)</code>是否符合给定的正则表达式（和<code>unittest</code>中的<code>TestCase.assertRaisesRegexp</code>方法类似）：</p>
<pre><code><code>import pytest


def myfunc():
    raise ValueError(&quot;Exception 123 raised&quot;)


def test_match():
    with pytest.raises((ValueError, RuntimeError), match=r&#39;.* 123 .*&#39;):
        myfunc()</code></pre>
<p>pytest实际调用的是<code>re.search()</code>方法来做上述检查；并且，<code>pytest.raises()</code>也支持检查多个期望异常（以元组的形式传递参数），我们只需要触发其中任意一个；</p>
<p><code>pytest.raises</code>还有另外的一种使用形式：</p>
<ul>
<li><p>首先，我们来看一下它在源码中的定义：</p>
<pre><code><code># _pytest/python_api.py

def raises(  # noqa: F811
    expected_exception: Union[&quot;Type[_E]&quot;, Tuple[&quot;Type[_E]&quot;, ...]],
    *args: Any,
    match: Optional[Union[str, &quot;Pattern&quot;]] = None,
    **kwargs: Any
) -&gt; Union[&quot;RaisesContext[_E]&quot;, Optional[_pytest._code.ExceptionInfo[_E]]]:</code></pre>
<p>它接收一个位置参数<code>expected_exception</code>，一组可变参数<code>args</code>，一个关键字参数<code>match</code>和一组关键字参数<code>kwargs</code>；</p></li>
<li><p>接着看方法的具体内容：</p>
<pre><code><code># _pytest/python_api.py

    if not args:
        if kwargs:
            msg = &quot;Unexpected keyword arguments passed to pytest.raises: &quot;
            msg += &quot;, &quot;.join(sorted(kwargs))
            msg += &quot;\nUse context-manager form instead?&quot;
            raise TypeError(msg)
        return RaisesContext(expected_exception, message, match)
    else:
        func = args[0]
        if not callable(func):
            raise TypeError(
                &quot;{!r} object (type: {}) must be callable&quot;.format(func, type(func))
            )
        try:
            func(*args[1:], **kwargs)
        except expected_exception as e:
            # We just caught the exception - there is a traceback.
            assert e.__traceback__ is not None
            return _pytest._code.ExceptionInfo.from_exc_info(
                (type(e), e, e.__traceback__)
            )
    fail(message)</code></pre>
<p>其中，<code>args</code>如果存在，那么它的第一个参数必须是一个可调用的对象，否则会报<code>TypeError</code>异常；</p>
<p>同时，它会把剩余的<code>args</code>参数和所有<code>kwargs</code>参数传递给这个可调用对象，然后检查这个对象执行之后是否触发指定异常；</p></li>
<li><p>所以我们有了一种新的写法：</p>
<pre><code><code>pytest.raises(ZeroDivisionError, lambda x: 1/x, 0)

# 或者

pytest.raises(ZeroDivisionError, lambda x: 1/x, x=0)</code></pre>
<p>这个时候如果你再传递<code>match</code>参数，是不生效的，因为它只有在<code>if not args:</code>的时候生效；</p></li>
</ul>
<p><code>pytest.mark.xfail()</code>也可以接收一个<code>raises</code>参数，来判断用例是否因为一个具体的异常而导致失败：</p>
<pre><code><code>@pytest.mark.xfail(raises=IndexError)
def test_f():
    f()</code></pre>
<p>如果<code>f()</code>触发一个<code>IndexError</code>异常，则用例标记为<code>xfailed</code>；如果没有，则正常执行<code>f()</code>；</p>
<blockquote>
<p>注意：</p>
<ul>
<li><p>如果<code>f()</code>测试成功，用例的结果是<code>xpassed</code>，而不是<code>passed</code>；</p></li>
<li><p><code>pytest.raises</code>适用于检查由代码故意引发的异常；而<code>@pytest.mark.xfail()</code>更适合用于记录一些未修复的<code>Bug</code>；</p></li>
</ul>
</blockquote>
<h2 id="特殊数据结构比较时的优化">3. 特殊数据结构比较时的优化</h2>
<pre><code><code># src/chapter-3/test_special_compare.py

def test_set_comparison():
    set1 = set(&#39;1308&#39;)
    set2 = set(&#39;8035&#39;)
    assert set1 == set2


def test_long_str_comparison():
    str1 = &#39;show me codes&#39;
    str2 = &#39;show me money&#39;
    assert str1 == str2


def test_dict_comparison():
    dict1 = {
        &#39;x&#39;: 1,
        &#39;y&#39;: 2,
    }
    dict2 = {
        &#39;x&#39;: 1,
        &#39;y&#39;: 1,
    }
    assert dict1 == dict2</code></pre>
<p>上面，我们检查了三种数据结构的比较：集合、字符串和字典；</p>
<pre class="bash"><code>$ pipenv run pytest -q src/chapter-3/test_special_compare.py 
FFF                                                               [100%]
=============================== FAILURES ================================
__________________________ test_set_comparison __________________________

    def test_set_comparison():
        set1 = set(&#39;1308&#39;)
        set2 = set(&#39;8035&#39;)
&gt;       assert set1 == set2
E       AssertionError: assert {&#39;0&#39;, &#39;1&#39;, &#39;3&#39;, &#39;8&#39;} == {&#39;0&#39;, &#39;3&#39;, &#39;5&#39;, &#39;8&#39;}
E         Extra items in the left set:
E         &#39;1&#39;
E         Extra items in the right set:
E         &#39;5&#39;
E         Full diff:
E         - {&#39;8&#39;, &#39;0&#39;, &#39;1&#39;, &#39;3&#39;}
E         + {&#39;8&#39;, &#39;3&#39;, &#39;5&#39;, &#39;0&#39;}

src/chapter-3/test_special_compare.py:26: AssertionError
_______________________ test_long_str_comparison ________________________

    def test_long_str_comparison():
        str1 = &#39;show me codes&#39;
        str2 = &#39;show me money&#39;
&gt;       assert str1 == str2
E       AssertionError: assert &#39;show me codes&#39; == &#39;show me money&#39;
E         - show me codes
E         ?         ^ ^ ^
E         + show me money
E         ?         ^ ^ ^

src/chapter-3/test_special_compare.py:32: AssertionError
_________________________ test_dict_comparison __________________________

    def test_dict_comparison():
        dict1 = {
            &#39;x&#39;: 1,
            &#39;y&#39;: 2,
        }
        dict2 = {
            &#39;x&#39;: 1,
            &#39;y&#39;: 1,
        }
&gt;       assert dict1 == dict2
E       AssertionError: assert {&#39;x&#39;: 1, &#39;y&#39;: 2} == {&#39;x&#39;: 1, &#39;y&#39;: 1}
E         Omitting 1 identical items, use -vv to show
E         Differing items:
E         {&#39;y&#39;: 2} != {&#39;y&#39;: 1}
E         Full diff:
E         - {&#39;x&#39;: 1, &#39;y&#39;: 2}
E         ?               ^
E         + {&#39;x&#39;: 1, &#39;y&#39;: 1}...
E         
E         ...Full output truncated (2 lines hidden), use &#39;-vv&#39; to show

src/chapter-3/test_special_compare.py:44: AssertionError
3 failed in 0.08s</code></pre>
<p>针对一些特殊的数据结构间的比较，<code>pytest</code>对结果的显示做了一些优化：</p>
<ul>
<li>集合、列表等：标记出第一个不同的元素；</li>
<li>字符串：标记出不同的部分；</li>
<li>字典：标记出不同的条目；</li>
</ul>
<h2 id="为失败断言添加自定义的说明">4. 为失败断言添加自定义的说明</h2>
<pre><code><code># src/chapter-3/test_foo_compare.py

class Foo:
    def __init__(self, val):
        self.val = val

    def __eq__(self, other):
        return self.val == other.val
    
    
def test_foo_compare():
    f1 = Foo(1)
    f2 = Foo(2)
    assert f1 == f2</code></pre>
<p>我们定义了一个<code>Foo</code>对象，也复写了它的<code>__eq__()</code>方法，但当我们执行这个用例时：</p>
<pre class="bash"><code>$ pipenv run pytest -q src/chapter-3/test_foo_compare.py 
F                                                                 [100%]
=============================== FAILURES ================================
___________________________ test_foo_compare ____________________________

    def test_foo_compare():
        f1 = Foo(1)
        f2 = Foo(2)
&gt;       assert f1 == f2
E       assert &lt;test_foo_compare.Foo object at 0x10ecae860&gt; == &lt;test_foo_compare.Foo object at 0x10ecae748&gt;

src/chapter-3/test_foo_compare.py:34: AssertionError
1 failed in 0.05s</code></pre>
<p>并不能直观的从中看出来失败的原因<code>assert &lt;test_foo_compare.Foo object at 0x10ecae860&gt; == &lt;test_foo_compare.Foo object at 0x10ecae748&gt;</code>；</p>
<p>在这种情况下，我们有两种方法来解决：</p>
<ul>
<li><p>复写<code>Foo</code>的<code>__repr__()</code>方法：</p>
<pre><code><code>def __repr__(self):
    return str(self.val)</code></pre>
<p>我们再执行用例：</p>
<pre><code><code>$ pipenv run pytest -q src/chapter-3/test_foo_compare.py 
F                                                                 [100%]
=============================== FAILURES ================================
___________________________ test_foo_compare ____________________________

    def test_foo_compare():
        f1 = Foo(1)
        f2 = Foo(2)
&gt;       assert f1 == f2
E       assert 1 == 2

src/chapter-3/test_foo_compare.py:37: AssertionError
1 failed in 0.05s</code></pre>
<p>这时，我们能看到失败的原因是因为<code>1 == 2</code>不成立；</p>
<blockquote>
<p>至于<code>__str__()</code>和<code>__repr__()</code>的区别，可以参考<code>StackFlow</code>上的这个问题中的回答：<a href="https://stackoverflow.com/questions/1436703/difference-between-str-and-repr" class="uri">https://stackoverflow.com/questions/1436703/difference-between-str-and-repr</a></p>
</blockquote></li>
<li><p>使用<code>pytest_assertrepr_compare</code>这个钩子方法添加自定义的失败说明</p>
<pre><code><code># src/chapter-3/test_foo_compare.py

from .test_foo_compare import Foo


def pytest_assertrepr_compare(op, left, right):
    if isinstance(left, Foo) and isinstance(right, Foo) and op == &quot;==&quot;:
        return [
            &quot;比较两个Foo实例:&quot;,  # 顶头写概要
            &quot;   值: {} != {}&quot;.format(left.val, right.val),  # 除了第一个行，其余都可以缩进
        ]</code></pre>
<p>再次执行：</p>
<pre><code><code>$ pytest -q src/chapter-3/test_foo_compare.py 
F                                                                 [100%]
=============================== FAILURES ================================
___________________________ test_foo_compare ____________________________

    def test_foo_compare():
        f1 = Foo(1)
        f2 = Foo(2)
&gt;       assert f1 == f2
E       assert 比较两个Foo实例:
E            值: 1 != 2

src/chapter-3/test_foo_compare.py:37: AssertionError
1 failed in 0.03s</code></pre>
<p>我们会看到一个更友好的失败说明；</p></li>
</ul>
<h2 id="关于断言自省的细节">5. 关于断言自省的细节</h2>
<p>当断言失败时，<code>pytest</code>为我们提供了非常人性化的失败说明，中间往往夹杂着相应变量的自省信息，这个我们称为断言的自省；</p>
<p>那么，<code>pytest</code>是如何做到这样的：</p>
<ul>
<li><code>pytest</code>发现测试模块，并引入他们，与此同时，<code>pytest</code>会复写断言语句，添加自省信息；但是，不是测试模块的断言语句并不会被复写；</li>
</ul>
<h3 id="复写缓存文件">5.1. 复写缓存文件</h3>
<p><code>pytest</code>会把被复写的模块存储到本地作为缓存使用，你可以通过在测试用例的根文件夹中的<code>conftest.py</code>里添加如下配置来禁止这种行为；：</p>
<pre><code><code>import sys

sys.dont_write_bytecode = True</code></pre>
<p>但是，它并不会妨碍你享受断言自省的好处，只是不会在本地存储<code>.pyc</code>文件了。</p>
<h3 id="去使能断言自省">5.2. 去使能断言自省</h3>
<p>你可以通过一下两种方法：</p>
<ul>
<li>在需要去使能模块的<code>docstring</code>中添加<code>PYTEST_DONT_REWRITE</code>字符串；</li>
<li>执行pytest时，添加<code>--assert=plain</code>选项；</li>
</ul>
<p>我们来看一下去使能后的效果：</p>
<pre class="bash"><code>$ pipenv run pytest -q --assert=plain src/chapter-3/test_foo_compare.py 
F                                                                 [100%]
=============================== FAILURES ================================
___________________________ test_foo_compare ____________________________

    def test_foo_compare():
        f1 = Foo(1)
        f2 = Foo(2)
&gt;       assert f1 == f2
E       AssertionError

src/chapter-3/test_foo_compare.py:37: AssertionError
1 failed in 0.03s</code></pre>
<p>断言失败时的信息就非常的不完整了，我们几乎看不出任何有用的调试信息；</p>
<blockquote>
<p>GitHub仓库地址：<a href="https://github.com/luizyao/pytest-chinese-doc" class="uri">https://github.com/luizyao/pytest-chinese-doc</a></p>
</blockquote>
</div>
</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>