<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修Python——raise引发异常' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>Python——raise引发异常</center></div><div class='banquan'>原文出处:本文由博客园博主C、小明提供。<br/>
原文连接:https://www.cnblogs.com/mingmingming/p/11254596.html</div><br>
    <p>程序出现错误，会自动引发异常，Python也允许使用raise语句自行引发异常。</p>
<h3>一、使用raise引发异常</h3>
<p>单独一个raise引发异常，默认引发RuntimeError异常，例：</p>
<div class="cnblogs_Highlighter">
<pre><code>try:
	print ('正在运行try块...')
	raise
	print ('不再运行...')
except Exception as e:
	print ('正在运行except块...')

# 运行结果
正在运行try块...
正在运行except块...
</pre>
</div>
<p>raise后带一个异常类，引发指定异常类的默认实例，例：</p>
<div class="cnblogs_Highlighter">
<pre><code>def test():
	try:
		print ('正在运行try块...')
		raise SyntaxError('引发指定异常...')
		print ('不再运行...')
	except TypeError as e:
		print ('对类型无效的操作...',e)
	except ValueError as e:
		print ('传入无效的参数...',e)
	except SyntaxError as e:
		print ('语法错误...',e)

test()

# 运行结果
正在运行try块...
语法错误... 引发指定异常...
</pre>
</div>
<h3>二、自定义异常类</h3>
<p>Python运行自定义异常类，自定义异常都应该继承Exception基类或Exception的子类，自定义类大部分情况下都可以采用AuctionException.py类似的代码来完成，只要改变AuctionException异常的类名即可（使类名更准确的描述该异常）。</p>
<p>自定义一个异常类，例：</p>
<div class="cnblogs_Highlighter">
<pre><code>class CustomException(Exception):
	pass

def test():
	try:
		raise CustomException
	except CustomException:
		print ('触发异常...')

test()
# 运行结果
触发异常...
</pre>
</div>
<h3>三、except和raise组合使用</h3>
<p>当出现一个异常时，单单靠一个方法无法完全处理该异常，必须使用几个方法协作才能完全处理该异常时，就用到except块结合raise语句来完成。</p>
<p>例：</p>
<div class="cnblogs_Highlighter">
<pre><code># 自定义异常
class CustomException(Exception):
	pass

class Test:
	def custom(self):
		try:
			aaa
		except Exception as e:
			print ('出现异常：',e)
			raise CustomException('触发自定义异常~')

def test():
	T = Test()
	try:
		T.custom()
	except CustomException as e:
		print ('test函数捕获异常；',e)

test()
# 打印
出现异常： name 'aaa' is not defined
test函数捕获异常； 触发自定义异常~
</pre>
</div>
<p>　　上面程序中，aaa触发了NameError异常，执行Test类中的except块，打印错误信息后，通知该方法调用者再次处理CustomException异常，所以custom()方法的调用者test()函数可以再次捕获CustomException异常，把异常详细信息打印出来。</p>
</div>
</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>