<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修Python自动化学习--异常提示' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>Python自动化学习--异常提示</center></div><div class='banquan'>原文出处:本文由博客园博主小哈别闹提供。<br/>
原文连接:https://www.cnblogs.com/LT-XILI/p/11578684.html</div><br>
    <p>举例：打开一个不存在的文件时：</p>
<div class="cnblogs_Highlighter">
<pre><code>&gt;&gt;open("abc.txt","r")<br />会提示错误</pre>
<p>Traceback (most recent call last):<br />  File "D:/project1/test.py", line 11, in &lt;module&gt;<br />    open("abc.txt","r")<br />FileNotFoundError: [Errno 2] No such file or directory: 'abc.txt'</p>





</div>
<p>这时可以用 try....except 语句来捕捉并处理这个异常</p>
<div class="cnblogs_Highlighter">
<pre><code>try:
    open("abc.txt","r")
except FileNotFoundError:
    print("出错啦")
----------------------
#这时运行就只会打印&ldquo;出错啦&rdquo;
</pre>
</div>
<p>如果将语句换成：</p>
<div class="cnblogs_Highlighter">
<pre><code>try:
    print(a)
except FileNotFoundError:
    print("出错啦")

----------------------
Traceback (most recent call last):
File "D:/project1/test.py", line 12, in &lt;module&gt;
print(a)
NameError: name 'a' is not defined</pre>
</div>
<p>运行时还是报错了，这时因为&ldquo;FileNotFoundError&rdquo;是表示找不到文件时的报错，跟现在的&ldquo;NameError&rdquo;不符，所以代码改成如下所示就行了：</p>
<div class="cnblogs_Highlighter">
<pre><code>try:
    print(a)
except NameError:
    print("出错啦")
</pre>
</div>
<p>但是，在Python中，所有的异常都继承于<strong>Exception</strong>,自2.5版本之后，出现的新的基类<strong>BaseException</strong>，新的基类可以接收所有的异常：</p>
<div class="cnblogs_Highlighter">
<pre><code>try:
    print(a)
    open("abc.txt","r")
except BaseException:
    print("出错啦")
-------------------------
#不管那一行出现异常，都能捕捉到并打印&ldquo;出错啦&rdquo;，但是并不能知道哪一行的语句出错，这时我们可以打印异常信息：
try:
    print(a)
    open("abc.txt","r")
except BaseException as msg:
　　print(msg)
　　print("出错啦")
-------------------------
[Errno 2] No such file or directory: 'abc.txt'
</pre>
</div>
<p>以下列出Python中常见的异常：</p>
<table style="height: 242px; border-color: #000000; border-width: 0px; width: 787px; border-style: solid;" border="0" frame="border">
<tbody>
<tr>
<td>BaseException</td>
<td>新的所有异常类的基类</td>
</tr>
<tr>
<td>Exception</td>
<td>所有异常的基类，但继承自BaseException</td>
</tr>
<tr>
<td>AssertionError</td>
<td>asser语句失败</td>
</tr>
<tr>
<td>FileNotFoundError</td>
<td>试图打开一个不存的文件或目录</td>
</tr>
<tr>
<td>AttributeError</td>
<td>试图访问的对象没有属性</td>
</tr>
<tr>
<td>OSError</td>
<td>当系统函数返回一个系统相关的错误（包括I/O故障），如&ldquo;找不到文件&rdquo;或&ldquo;磁盘已满&rdquo;时，引发此异常</td>
</tr>
<tr>
<td>NameError</td>
<td>使用一个还未赋值对象的变量</td>
</tr>
<tr>
<td>IndexError</td>
<td>当一个序列超出范围时引发此异常</td>
</tr>
<tr>
<td>SyntaxError</td>
<td>当解析器遇到一个语法错误时引发此异常</td>
</tr>
<tr>
<td>KeyboardInterrupt</td>
<td>组合键Ctrl+C被按下，程序被强制终止</td>
</tr>
<tr>
<td>TypeError</td>
<td>传入的对象类型与要求不符</td>
</tr>
</tbody>
</table>
<p>异常结合<strong>else</strong>的用法：</p>
<div class="cnblogs_Highlighter">
<pre><code>try:
    a ="异常测试："
    print(a)
except NameError as msg:
    print(msg)
esle:
    print("没有异常时执行")
------------------------------
#当出现异常时，打印异常信息&ldquo;msg&rdquo;，当没有异常时，执行esle，打印&ldquo;没有异常时执行&rdquo;
</pre>
</div>
<p>异常结合<strong>finallyd</strong>的用法：</p>
<div class="cnblogs_Highlighter">
<pre><code>try:
    print(a)
except NameError as msg:
    print(msg)
finally:
    print("不管有无异常，都执行finally)</pre>
</div>
<p>用户自定义的异常抛出&nbsp;<strong>raise</strong>:</p>
<div class="cnblogs_Highlighter">
<pre><code>class loogExcept(Exception):
    def __init__(self,leng):
        self.leng = leng

    def __str__(self):
        print("你的名字："+str(self.leng)+",超过长度啦！")

def name_Test():
    try:
        name = input("enter your name:")
        if len(name) &gt; 4:
            raise loogExcept(len(name))
        else:
            print(name)
    except loogExcept as e_result:
        print("捕捉到异常啦")
        print("打印异常：",e_result)

if __name__ == "__main__":
    name_Test()
---------------------------------------------
enter your name:sadsadasd
捕捉到异常啦
打印异常： 你的名字：9,超过长度啦！
你的名字：9,超过长度啦！
Traceback (most recent call last):
File "D:/project1/test.py", line 19, in name_Test
raise loogExcept(len(name))
__main__.loogExcept: &lt;exception str() failed&gt;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:/project1/test.py", line 27, in &lt;module&gt;
name_Test()
File "D:/project1/test.py", line 24, in name_Test
print("打印异常：",e_result)
TypeError: __str__ returned non-string (type NoneType)

Process finished with exit code 1
</pre>
</div>
<p>　　</p>
<p>　　</p>
<p>&nbsp;</p>
</div>
</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>